workflow:
  rules:
    - if: '$GITLAB_CI == "false"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "trigger"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never

stages:
  - build
  - deploy
  - operations
  - housekeeping
  - test

include:
  - local: 'gitlab/build.yml'
  - local: 'gitlab/deploy.yml'
  - local: 'gitlab/operations.yml'
  - local: 'gitlab/housekeeping.yml'
  - local: 'gitlab/test.yml'
