"""add professional to service

Revision ID: 020
Revises: 019
Create Date: 2026-01-21 14:24:35.824594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020'
down_revision: Union[str, None] = '019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('professional', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'professional')
    # ### end Alembic commands ###
