"""update user info

Revision ID: 022
Revises: 021
Create Date: 2026-01-26 15:36:15.866135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022'
down_revision: Union[str, None] = '021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_user_info', 'city',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('customer_user_info', 'address',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('customer_user_info', 'tax_code',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('customer_user_info', 'company_name',
               existing_type=sa.String(),
               nullable=True)
    op.add_column('customer_user_info', sa.Column('email', sa.String(), nullable=True))
    op.execute("""
      UPDATE customer_user_info
      SET email = "user".email
      FROM "user"
      WHERE customer_user_info.user_id = "user".id
        AND "user".email IS NOT NULL
    """)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), autoincrement=False, nullable=True))
    op.execute("""
      UPDATE "user"
      SET email = customer_user_info.email
      FROM customer_user_info
      WHERE customer_user_info.user_id = "user".id
        AND customer_user_info.email IS NOT NULL
    """)
    op.drop_column('customer_user_info', 'email')
    op.alter_column('customer_user_info', 'company_name',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('customer_user_info', 'tax_code',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('customer_user_info', 'address',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('customer_user_info', 'city',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###
