"""update_delivery_group

Revision ID: 62b67398bd62
Revises: 981eba745ab5
Create Date: 2025-10-06 15:46:52.653894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62b67398bd62'
down_revision: Union[str, None] = '981eba745ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('delivery_group', sa.Column('schedule_id', sa.Integer(), nullable=False))
  op.create_foreign_key(None, 'delivery_group', 'schedule', ['schedule_id'], ['id'])
  op.drop_constraint(op.f('italco_user_delivery_group_id_fkey'), 'italco_user_id', type_='foreignkey')
  op.drop_column('italco_user', 'delivery_group_id')
  op.drop_constraint(op.f('schedule_delivery_group_id_fkey'), 'schedule', type_='foreignkey')
  op.drop_column('schedule', 'delivery_group_id')
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('schedule', sa.Column('delivery_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
  op.create_foreign_key(op.f('schedule_delivery_group_id_fkey'), 'schedule', 'delivery_group', ['delivery_group_id'], ['id'])
  op.add_column('italco_user', sa.Column('delivery_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
  op.create_foreign_key(op.f('italco_user_delivery_group_id_fkey'), 'italco_user_id', 'delivery_group', ['delivery_group_id'], ['id'])
  op.drop_constraint(None, 'delivery_group', type_='foreignkey')
  op.drop_column('delivery_group', 'schedule_id')
  # ### end Alembic commands ###

