"""update delivery group

Revision ID: 6e5bf22fe99a
Revises: 981eba745ab5
Create Date: 2025-10-09 16:04:31.031537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e5bf22fe99a'
down_revision: Union[str, None] = '981eba745ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_group', sa.Column('schedule_id', sa.Integer(), nullable=False))
    op.add_column('delivery_group', sa.Column('italco_user_id', sa.Integer(), nullable=False))
    op.drop_column('delivery_group', 'lat')
    op.drop_column('delivery_group', 'lon')
    op.drop_column('delivery_group', 'name')
    op.add_column('italco_user', sa.Column('lat', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('italco_user', sa.Column('lon', sa.Numeric(precision=11, scale=8), nullable=True))
    op.create_foreign_key(None, 'delivery_group', 'italco_user', ['italco_user_id'], ['id'])
    op.create_foreign_key(None, 'delivery_group', 'schedule', ['schedule_id'], ['id'])
    op.drop_constraint(op.f('italco_user_delivery_group_id_fkey'), 'italco_user', type_='foreignkey')
    op.drop_column('italco_user', 'delivery_group_id')
    op.drop_constraint(op.f('schedule_delivery_group_id_fkey'), 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'delivery_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('delivery_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('schedule_delivery_group_id_fkey'), 'schedule', 'delivery_group', ['delivery_group_id'], ['id'])
    op.add_column('italco_user', sa.Column('delivery_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('italco_user_delivery_group_id_fkey'), 'italco_user', 'delivery_group', ['delivery_group_id'], ['id'])
    op.drop_constraint(None, 'delivery_group', type_='foreignkey')
    op.drop_constraint(None, 'delivery_group', type_='foreignkey')
    op.drop_column('delivery_group', 'italco_user_id')
    op.drop_column('delivery_group', 'schedule_id')
    op.drop_column('italco_user', 'lon')
    op.drop_column('italco_user', 'lat')
    op.add_column('delivery_group', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('delivery_group', sa.Column('lon', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
    op.add_column('delivery_group', sa.Column('lat', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
