"""Da eliminare

Revision ID: a36cd7fa90bb
Revises: 015
Create Date: 2025-12-06 16:31:05.659797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36cd7fa90bb'
down_revision: Union[str, None] = '015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_group', sa.Column('delivery_user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_delivery_group_user'), 'delivery_group', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_group', 'delivery_user', ['delivery_user_id'], ['id'])
    op.drop_column('delivery_group', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_group', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'delivery_group', type_='foreignkey')
    op.create_foreign_key(op.f('fk_delivery_group_user'), 'delivery_group', 'user', ['user_id'], ['id'])
    op.drop_column('delivery_group', 'delivery_user_id')
    # ### end Alembic commands ###
