"""Schedule

Revision ID: 5ba3c095aaf6
Revises: 6855ce8e924d
Create Date: 2025-05-19 21:56:34.823629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ba3c095aaf6'
down_revision: Union[str, None] = '6855ce8e924d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('delivery_group_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['delivery_group_id'], ['delivery_group.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transport_delivery_group')
    op.add_column('order', sa.Column('schedule_id', sa.Integer(), nullable=False))
    op.drop_constraint('order_delivery_group_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'schedule', ['schedule_id'], ['id'])
    op.drop_column('order', 'delivery_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_delivery_group_id_fkey', 'order', 'delivery_group', ['delivery_group_id'], ['id'])
    op.drop_column('order', 'schedule_id')
    op.create_table('transport_delivery_group',
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transport_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delivery_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['delivery_group_id'], ['delivery_group.id'], name='transport_delivery_group_delivery_group_id_fkey'),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], name='transport_delivery_group_transport_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transport_delivery_group_pkey')
    )
    op.drop_table('schedule')
    # ### end Alembic commands ###
